# Generated by Django 4.2 on 2023-12-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтверждение по элетронной почте', 'verbose_name_plural': 'Подтверждение по элетронной почте'},
        ),
    ]
